### ISSUE TITLE
大佬好啊，刚接触到模板，发现许多模板不好用，这个类似smarty模板语法挺好的

### ISSUE THREAD

**Issue by aiweisir** [fefit/fet#1]
大佬好啊，刚接触到模板，发现许多模板不好用，这个类似smarty模板语法挺好的有交流群吗，跟您学习学习

**Comment by fefit** [comment]
您太谦虚了！因为是最近才开发的项目，目前功能还在完善中，估计最近一到两周内会发一个测试覆盖较高的版本出来。交流群暂时没有，如果大家喜欢，晚点会建一个将群号发到README里。感谢支持！欢迎随时反馈遇到的问题~！
